specfile_path: cockpit-podman.spec
synced_files:
  - cockpit-podman.spec
upstream_package_name: cockpit-podman
downstream_package_name: cockpit-podman
actions:
  post-upstream-clone: make cockpit-podman.spec
  create-archive: make dist-gzip
jobs:
  - job: tests
    trigger: pull_request
    metadata:
      targets:
      # XXX: use fedora-all once this works
      - fedora-33
